<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<ul class="items">
	<?php foreach($this->items as $item): ?>
	<li>
		<a href="<?php echo JRoute::_(JE_ContentHelperRoute::getArticleRoute($item->slug, $item->catid)); ?>">
			<?php echo $this->escape($item->title); ?>
		</a>			
	</li>
	<li>
	<?php echo $this->escape($item->category_title); ?>
	</li>
	<li>
		<?php if ($item->images): ?>
		<img src="<?php echo JURI::base().$item->images; ?>" style="float:left; margin-right: 10px; width: 100px;" />
		<?php endif; ?>
		<?php echo $item->introtext; ?>
	</li>
	<li>
		Detail
	</li>
	<?php endforeach; ?>
</ul>

<div class="pagination">
	<?php echo $this->pagination->getPagesLinks(); ?>
</div>