<?php
/**
 * @version		$Id: categories.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Categories model for the je_content component.
 *
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @since		1.6
 */
class JE_ContentModelCategories extends JModel
{
    public function getArticles()
    {
	$db = JFactory::getDbo();
	$query = $db->getQuery(true);

	$query->select('*')
		->from('#__categories')
		->where('extension = "com_je_content"')
		->where('published = 1')
		->order('lft')
	    ;

	$db->setQuery($query);
	$categories = $db->loadObjectList();

	$arrCat = array();

	$idx = 0;

	foreach ($categories as $category)
	{
	    if ($category->level == 1)
		$arrCat[$category->id]['category'] = $category;
	    else
	    {
//		if ($category->featured == 0)
//		    continue;

		$query = $db->getQuery(true);

		$query->select('id, catid, title, alias, introtext, images')
			->from('#__je_content')
			->where('catid = ' . $category->id)
			->where('state = 1')
		    ;

		$db->setQuery($query, 0, 3);
		$rs = $db->loadObjectList();

		if (!empty($rs))
		{
		    $arrCat[$category->parent_id]['sub'][$category->id] = $category;
		    $arrCat[$category->parent_id]['articles'][$category->id] = $rs;
		}

	    }

	    $idx ++;
	}

	return $arrCat;
    }
}