<?php
/**
 * @version		$Id: categories.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Categories model for the je_content component.
 *
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @since		1.6
 */
class JE_ContentModelCategories extends JModelList
{
	/**
	 * Gets a list of categories
	 *
	 * @return	array	An array of categories objects.
	 * @since	1.6
	 */
	function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'#__je_content.id , #__je_content.title, #__je_content.alias'
		);
		
		$query->from('`#__je_content`');
		
		

		return $query;
	}
}