<?php
/**
 * @version		$Id: featured.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Featured model for the je_content component.
 *
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @since		1.6
 */
class JE_ContentModelFeatured extends JModelList
{
	/**
	 * Gets a list of featured
	 *
	 * @return	array	An array of featured objects.
	 * @since	1.6
	 */
	public function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'a.id , a.title, a.alias, a.introtext, a.featured_images'
		);
		
		$query->from('`#__je_content` a');
		
		// Join over the categories
		$query->select('c.title AS category_title');
		$query->join('INNER', '#__categories AS c ON c.id = a.catid');
		
		$query->where('a.featured = 1');
		
		$query->order('a.id DESC');

		return $query;
	}
	
	public function getItems()
	{
		$db = JFactory::getDbo();
		$query = $this->getListQuery();
		
		$db->setQuery($query, 0, 10);
		$rs = $db->loadObjectList();
		
		return $rs;
	}
}