<?php
/**
 * @version		$Id: view.html.php $
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.view');

/**
 * Article View class for the je_content component
 *
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @since		1.5
 */
class JE_ContentViewArticle extends JView
{
	protected $item;

	function display($tpl = null)
	{
		// Initialise variables.
		$item = $this->get('Item');
		
		$item->slug = $item->alias ? ($item->id . ':' . $item->alias) : $item->id;
		
		$this->item = $item;
		
		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseWarning(500, implode("\n", $errors));
			return false;
		}

		$this->_prepareDocument();

		parent::display($tpl);
	}

	/**
	 * Prepares the document
	 */
	protected function _prepareDocument()
	{
		//TODO: prepare document
	}
}
