<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<div class="icons news-featured">
	<div class="left-panel float-left padding-5">
		<div>
			<?php
			$modules = JModuleHelper::getModules('blogger');
			foreach( $modules As $mod ){
			   echo  $mod->content;
			}
			?>
		</div>
	</div>
	
	<div class="right-panel float-right padding-5">
		<ul class="items">
			<?php foreach($this->items as $item): ?>
				<li>
					<h1><?php echo $this->escape($item->title); ?>
				</li>
				<li>
				<?php echo JHtml::_('string.truncate', strip_tags($item->introtext), 100); ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<div class="clr"></div>

<div>
	<div class="left-side float-left">
		<div class="icons tab">
			<span>DỊCH VỤ CƯỚI</span>
		</div>
		<div>
			content
		</div>
	</div>
	
	<div class="right-side float-right">
		<div class="icons tab">
			<span>TIN TỨC</span>
		</div>
		<div>
			content
		</div>
	</div>
</div>

<div class="clr"></div>

<div class="clr"></div>

<div>
	<div class="left-side float-left">
		<h2>BLOG DOANH NGHIỆP</h2>
		<div>
			content
		</div>
	</div>
	
	<div class="right-side float-right">
		<h2>TIN CŨ</h2>
		<div>
			content
		</div>
	</div>
</div>

<div class="clr"></div> 