<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<script type="text/javascript" src="<?php echo JURI::base(); ?>media/jquery.bxslider/jquery.bxslider.min.js"></script>



<div class="icons news-featured">
	<div class="left-panel float-left padding-5">
		<div>
			<?php
			$modules = JModuleHelper::getModules('blogger');
			foreach( $modules As $mod ){
			   echo  $mod->content;
			}
			?>
		</div>
	</div>
	
	<div class="right-panel float-right padding-5">
		<ul class="items">
			<?php foreach($this->items as $item): ?>
				<li>
					<h1><?php echo $this->escape($item->title); ?>
				</li>
				<li>
				<?php echo JHtml::_('string.truncate', strip_tags($item->introtext), 100); ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<div class="clr"></div>

<div>
	<div class="left-side float-left">
        <?php
        $modules = JModuleHelper::getModules('wedding_services');
        foreach( $modules As $mod ){
            echo JModuleHelper::renderModule($mod);
        }
        ?>
	</div>
	
	<div class="right-side float-right">
		<div class="tab">
			<span class="icons">TIN TỨC</span>
		</div>
		<div class="content float-left">
			
			<div class="content-detail float-left margin-right-10">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>

			<div class="content-detail float-left">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>
			
		</div>
		
		<div class="content float-left margin-top-10">
			
			<div class="content-detail float-left margin-right-10">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>

			<div class="content-detail float-left">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>
			
		</div>
		
		<div class="content float-left margin-top-10">
			
			<div class="content-detail float-left margin-right-10">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>

			<div class="content-detail float-left">
				<h2 class="title">CẨM NANG CƯỚI</h2>
				<div class="round-4-conners-5 border-1 padding-5">
					<img src="images/sampledata/sample-2.png" />
					<h1>Tự tổ chức đám cưới</h1>
					<p class="content-desc">Tự tổ chức đám cưới dĩ nhiên sẽ vất vả hơn rất nhiều ...</p>
				</div>
			</div>
			
		</div>
	</div>
</div>

<div class="clr "></div>

<div class="hr margin-top-bottom-10"></div>

<div>
	<div class="left-side float-left">
        <?php
        $modules = JModuleHelper::getModules('business_blog');
        foreach( $modules As $mod ){
            echo JModuleHelper::renderModule($mod);
        }
        ?>
	</div>
	
	<div class="right-side float-right">
		<h2>TIN CŨ</h2>
		<div class="content">
			<div class="">
				<img src="" />
				<p>Đám cưới tập thể</p>
			</div>
		</div>
	</div>
</div>

<div class="clr"></div> 