<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

//get item
$item = $this->item;
?>

<div class="container">
    <div class="float-left left-side">
	<h1>
	    <a href="<?php echo JRoute::_(JE_ContentHelperRoute::getArticleRoute($item->slug, $item->catid)); ?>">
		    <?php echo $this->escape($item->title); ?>
	    </a>
	</h1>
	
	<div class="fulltext">
	    <?php echo $item->fulltext; ?>
	</div>
    </div>
    
    <div class="float-right right-side">
	<?php
	$modules = JModuleHelper::getModules('right');
	foreach( $modules As $mod ){
	    echo JModuleHelper::renderModule($mod);
	}
	?>
    </div>
</div>

<div class="clear"></div>