<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<div class="container">
    <div class="float-left left-side">
		<div>
		    <?php echo JEUtil::loadModule('center'); ?>
		</div>
		
		<div class="sub-container">
			<div class="left float-left">
			    <?php 
			    $articles = $this->articles;
			    
			    foreach ($articles as $item):
				if (isset($item['sub'])):
			    ?>
				<div class="items-category">
					<h1>
					    <?php
						$linkToCategory = '#';
						
					    $firstCategory = array_shift($item['sub']);
					    echo '<a href="'.$linkToCategory.'">'.$firstCategory->title.'</a>';

					    $tmp = array_reverse($item['sub']);
					    array_pop($tmp);
					    $categories = array_reverse($tmp);

					    $check = 0;
					    ?>
					    <span>
						    <?php foreach ($categories as $cat): ?>
						    <a href="#"><?php echo $cat->title; ?></a>

						    <?php 
						    $check ++;

						    if ($check > 1)
							break;

						    endforeach; 
						    ?>
					    </span>
					</h1>
					
					<div class="line-break-news"><span></span></div>

					<?php $listArticles = $item['articles'][$firstCategory->id]; ?>
					<div class="news-content">
						
						<div class="news-content-inside">
							<h2>
								<?php
								
								$slug = $listArticles[0]->alias ? ($listArticles[0]->id . ':' . $listArticles[0]->alias) : $listArticles[0]->id;
								
								?>
								
								<a href="<?php echo JRoute::_(JE_ContentHelperRoute::getArticleRoute($slug, $listArticles[0]->catid)); ?>">
									<?php echo $listArticles[0]->title; ?>
								</a>
							</h2>
							<?php echo $listArticles[0]->introtext; ?>
							
							<div class="clear"></div>
						</div>
					</div>
					
						
				</div>
			    <div class="clr"></div>
			    <?php endif; endforeach; ?>
			</div>
			
			<div class="right float-right">
			    <?php echo JEUtil::loadModule('right-sub', 'module-padding'); ?>
			</div>
		</div>
    </div>
    
    <div class="float-right right-side">
	<?php
	$modules = JModuleHelper::getModules('right');
	foreach( $modules As $mod ){
	    echo JModuleHelper::renderModule($mod);
	}
	?>
    </div>
</div>

<div class="clr"></div> 